services:
  backend:
    volumes:
      # Bind mount S3 directory to container
      # macOS: Host mounts S3 first, then bind mounts to container
      # Linux: Container mounts S3 internally to this bind-mounted directory
      - type: bind
        source: ${S3_MOUNT_DIR:-/opt/sentient}
        target: ${S3_MOUNT_DIR:-/opt/sentient}
    # FUSE capabilities for container-internal S3 mounting (Linux)
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
